delete from indicators_queue_region;
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Автономна республіка Крим', 'АР Крим');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Вінницька область', 'Вiнницька область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Вінницька область', 'Вінницька область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Вінницька область', 'Вінницька обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Вінницька область', 'Винницкая область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Вінницька область', 'ВІННИЦЬКА ОБЛ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Вінницька область', 'ВИННИЦКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Волинська область', 'Волинська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Волинська область', 'Волинська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Волинська область', 'Волынская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Волинська область', 'ВОЛЫНСКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Дніпропетровська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Днiпропетровська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Дніпропетровська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'ДНІПРОПЕТРОВСЬКА ОБЛ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'ДНЕПРОПЕТРОВСКАЯ ОБЛ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Днепропетровская область Украина');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Днепропетровская обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Днепропетровская');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Днепр');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Дніпропетровська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Днепропетровская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Дніпропетровька обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Січеславська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Січеславська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Січеславська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'СІЧЕСЛАВСЬКА ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'СІЧЕСЛАВСЬКА');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'СЕЧЕСЛАВСКАЯ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Дніпровська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'Дніпро');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Дніпропетровська область', 'ДНЕПРОПЕТРОВСКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Донецька область', 'Донецька область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Донецька область', 'Донецька обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Донецька область', 'ДОНЕЦЬКА ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Донецька область', 'ДОНЕЦЬКА ОБЛ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Донецька область', 'Донецкая область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Донецька область', 'Донецька');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Донецька область', 'ДОНЕЦКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Житомирська область', 'Житомирська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Житомирська область', 'Житомирська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Житомирська область', 'Житомирская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Житомирська область', 'Житомирська обл');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Житомирська область', 'Коростишівський');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Житомирська область', 'ЖИТОМИРСЬКА ОБЛ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Закарпатська область', 'Закарпатська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Закарпатська область', 'Закарпатська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Закарпатська область', 'Закарпатская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Закарпатська область', 'Закарпатська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Закарпатська область', 'ЗАКАРПАТСКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Запорізька область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Запорiзька область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Запорізька обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Запорізька');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Запорізька область Токмацький район');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Запорожская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Україна, Запорізька область,Чернігівський район');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Запорізька область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Запорізька область, Великобілозерський район');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Запорізька область  Токмацький район');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Україна, Запорізька область,Чернігівський район');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'ЗАПОРІЗЬКА ОБЛ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Запорізька область  Токмацький район');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Запорізька область', 'Великобілозерський район');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Івано-Франківська область', 'Івано-Франківська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Івано-Франківська область', 'Івано-Франківська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Івано-Франківська область', 'Ивано-Франковская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Івано-Франківська область', 'Галицький район Івано-Франківська обл');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Івано-Франківська область', 'Iвано-Франкiвська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Київська область', 'КИЕВСКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Київська область', 'Київська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Київська область', 'Київська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Київська область', 'Киевская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Київська область', 'Київська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Київська область', 'київська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Київська область', 'Київська обл');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Київська область', 'Киевская');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Кіровоградська область', 'Кiровоградська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Кіровоградська область', 'Кіровоградська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Кіровоградська область', 'КІРОВОГРАДСЬКА ОБЛ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Кіровоградська область', 'Кіровоградська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Кіровоградська область', 'Новомиргородський район');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Кіровоградська область', 'Кропивницька');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Кіровоградська область', 'Кировоградская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Луганська область', 'Луганська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Луганська область', 'ЛУГАНСКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Луганська область', 'Луганська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Луганська область', 'Луганская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Луганська область', 'ЛУГАНСЬКА ОБЛ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Львівська область', 'Львівська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Львівська область', 'Львівська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Львівська область', 'Львовская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Львівська область', 'Львiвська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Львівська область', 'ЛЬВОВСКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Львівська область', 'Львівська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Миколаївська область', 'Миколаївська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Миколаївська область', 'Миколаївська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Миколаївська область', 'Николаевская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Миколаївська область', 'смт.Воскресенське');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Миколаївська область', 'Врадіїївський район Миколаївська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Миколаївська область', 'Миколаївська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Одеська область', 'Одеська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Одеська область', 'Одеська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Одеська область', 'Одесская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Одеська область', 'Одесская обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Одеська область', 'Одеська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Одеська область', 'ОДЕССКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Одеська область', 'Одесская');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Полтавська область', 'Полтавська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Полтавська область', 'Полтавська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Полтавська область', 'Полтавська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Полтавська область', 'Полтавская');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Полтавська область', 'Полтавская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Полтавська область', 'ПОЛТАВСЬКА');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Рівненська область', 'Рівненська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Рівненська область', 'Рівненська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Рівненська область', 'Rivnens''ka oblast');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Рівненська область', 'Ровенская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Рівненська область', 'Рiвненська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Рівненська область', 'Рівненська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Сумська область', 'Сумська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Сумська область', 'Сумська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Сумська область', 'Сумська обл., Великописарівський р-н');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Сумська область', 'Сумская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Тернопільська область', 'Тернопільська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Тернопільська область', 'Тернопільська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Тернопільська область', 'Тернопольская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Тернопільська область', 'Тернопільська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Тернопільська область', 'Тернопiльська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Харківська область', 'Харківська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Харківська область', 'Харківська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Харківська область', 'Харкiвська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Харківська область', 'Харківська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Харківська область', 'ХАРКІВСЬКА ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Харківська область', 'Харьковская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Харківська область', 'Харьківська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Херсонська область', 'Херсонська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Херсонська область', 'Херсонская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Херсонська область', 'Херсонська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Херсонська область', 'Нижньосірогозький р-н Херсонської області');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Херсонська область', 'Херсонская');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Хмельницька область', 'Хмельницька область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Хмельницька область', 'Хмельницька обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Хмельницька область', 'ХМЕЛЬНИЦКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Хмельницька область', 'Хмельницька обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Хмельницька область', 'Хмельницкая область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Черкаська область', 'Черкаська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Черкаська область', 'Черкаська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Черкаська область', 'Черкасская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Черкаська область', 'Черкаська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Черкаська область', 'ЧЕРКАССКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Чернівецька область', 'Чернівецька область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Чернівецька область', 'Чернівецька обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Чернівецька область', 'Черновицкая область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Чернівецька область', 'Чернiвецька область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Чернівецька область', 'Боянчук');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Чернігівська область', 'Чернiгiвська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Чернігівська область', 'Чернігівська область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Чернігівська область', 'Чернігівська обл.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Чернігівська область', 'Чернігівська');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Чернігівська область', 'Черниговская область');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('Чернігівська область', 'ЧЕРНИГОВСКАЯ ОБЛ.');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'м.Київ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'м. Київ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'місто Київ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'Київ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'КИЇВ М');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'Киев');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'М. КИЇВ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'Україна');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'м. Київ');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'Державна');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'закупке');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'Відповідно до документації');
INSERT INTO public.indicators_queue_region (correct_name, original_name) VALUES ('м. Київ', 'Голосіївський район');
